[build]
  publish = "out"
  command = "npm run export"

[[redirects]]
  from = "https://ampproduct-static-blog-nextjs.netlify.app/"
  to = "https://amplience.com/blog"
  status = 301
  force = true
  
[[redirects]]
  from = "https://ampproduct-static-blog-nextjs.netlify.app/blog/*"
  to = "https://amplience.com/blog/:splat"
  status = 301
  force = true
